[package]
name = "spider_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
transport_iroh = ["spider_link/transport_iroh"]

[dependencies]
spider_link = { path="../spider_link", features = ["cs_0_x25519_chacha20", "transport_tcp"]}


tokio = { version = "1", features = ["full"] }
tracing = {version = "0.1", features = ["log"]}

serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"

cfg-if = "1.0.0"

lru = "0.12.5"

[dev-dependencies]
tracing-test = "0.2.5"
serial_test = "3.2.0"
