use std::{collections::HashMap, str::FromStr};

use bimap::BiHashMap;
use tracing::{info, trace};
use veilid_core::{
    DHTRecordDescriptor, DHTSchemaDFLT, FourCC, KeyPair, RouteId, Target, Timestamp, TimestampDuration, TypedKey, ValueSubkeyRangeSet, VeilidAPI, VeilidRouteChange
};

use crate::{error::ProblemWrap, LinkResult, SelfRelation};

use super::{introduction::VeilidIntroduction, pending::Introducible};

pub(crate) struct RouteManager {
    api: VeilidAPI,
    listen_dht: DHTRecordDescriptor,
    listen_route: Option<RouteId>,

    /// Map from incoming route ids to dht keys to allow refreshing when routes
    /// expire
    inc_connections: HashMap<RouteId, DHTRecordDescriptor>,

    /// BiMap between DHT keys and RouteIds
    out_connections: BiHashMap<TypedKey, RouteId>,
}

impl RouteManager {
    pub fn new(api: VeilidAPI, listen_dht: DHTRecordDescriptor) -> Self {
        Self {
            api,
            listen_dht,
            listen_route: None,
            inc_connections: HashMap::new(),
            out_connections: BiHashMap::new(),
        }
    }

    // Listen Route Items

    pub fn listen_route_initialized(&self) -> bool {
        trace!("Current listen route: {:?}", self.listen_route);
        self.listen_route.is_some()
    }

    pub async fn initialize_listen_routes(&mut self) -> LinkResult {
        trace!(
            "Listening at {}",
            &self.listen_dht.key()
        );

        if self.listen_route.is_none() {
            if let Ok(route_id) = self.initialize_inc_route(&self.listen_dht, 0).await {
                trace!("Listen route initialized with route id: {}", route_id);
                self.listen_route = Some(route_id);
            }else{
                trace!("Failed to initialize listen route");
            }
        }
        Ok(())
    }

    pub fn is_listen_route(&self, route: &RouteId) -> bool {
        self.listen_route.as_ref() == Some(route)
    }

    pub fn get_listen_dht_key(&self) -> &TypedKey {
        self.listen_dht.key()
    }

    // Incoming Route Items

    pub fn get_inc_dht(&self, route_id: &RouteId) -> Option<&DHTRecordDescriptor> {
        self.inc_connections.get(route_id)
    }

    pub async fn create_inc_route(&mut self) -> LinkResult<DHTRecordDescriptor> {
        let routing = self.api.routing_context().wrap()?;
        let schema = veilid_core::DHTSchema::DFLT(DHTSchemaDFLT::new(1).wrap()?);
        let dht = routing.create_dht_record(schema, None, None).await.wrap()?;
        let route_id = self.initialize_inc_route(&dht, 0).await?;
        self.inc_connections.insert(route_id, dht.clone());
        Ok(dht)
    }

    async fn initialize_inc_route(&self, dht: &DHTRecordDescriptor, index: u32) -> LinkResult<RouteId> {
        let (route_id, new_route_blob) = self
            .api
            .new_custom_private_route(
                &[FourCC::from_str("VLD0").unwrap()],
                veilid_core::Stability::Reliable,
                veilid_core::Sequencing::NoPreference,
            )
            .await
            .wrap()?;
        // self.api.import_remote_private_route(new_route_blob.clone()).expect("this blob was generated by us and is therefore valid");
        
        let routing = self.api.routing_context().wrap()?;
        info!("Opening dht record");
        let writer = Some(KeyPair::new(
            dht.owner().clone(),
            *dht.owner_secret().wrap()?,
        ));
        routing.open_dht_record(*dht.key(), writer).await.wrap()?;
        // info!("Setting DHT value to {:?}", new_route_blob);
        let result = routing
            .set_dht_value(*dht.key(), index, new_route_blob, None)
            .await;
        info!("Set DHT result: {:?}", result);
        Ok(route_id)
    }

    // Outgoing Route Items

    pub(crate) async fn send_listen_intro<I: Introducible>(
        &mut self,
        from_rel: &SelfRelation,
        pending: &I,
    ) -> LinkResult {
        trace!("Sending listen introduction to other side.");
        let intro = VeilidIntroduction::new_listen(
            from_rel,
            pending.to_rel(),
            *self.listen_dht.key(),
        );
        let msg = intro.serialize();
        self.send_msg(pending.to_dht(), msg).await
    }

    pub(crate) async fn send_connection_intro<I: Introducible>(
        &mut self,
        from_rel: &SelfRelation,
        pending: &I,
    ) -> LinkResult {
        trace!("Sending connection introduction to other side.");
        let intro = VeilidIntroduction::new_connection (
            from_rel,
            pending.to_rel(),
            *pending.dht_key(),
        );
        let msg = intro.serialize();
        self.send_msg(pending.to_dht(), msg).await
    }

    pub async fn send_msg(&mut self, dht_key: &TypedKey, msg: Vec<u8>) -> LinkResult {
        let route_id = self.load_outgoing_route(dht_key).await?;
        trace!("Sending to dht_key {} and route {}", dht_key, route_id);

        // Send Message
        let target = Target::PrivateRoute(route_id);
        self.api
            .routing_context()
            .wrap()?
            .app_message(target, msg)
            .await
            .wrap()
    }

    async fn load_outgoing_route(&mut self, dht_key: &TypedKey) -> LinkResult<RouteId> {
        // Get route_id
        // if let Some(route_id) = self.out_connections.get_by_left(dht_key) {
        //     return Ok(*route_id);
        // }

        let routing = self.api.routing_context().wrap()?;
        routing.open_dht_record(*dht_key, None).await.wrap()?;
        let dht_data = routing
            .get_dht_value(*dht_key, 0, true)
            .await
            .wrap()?
            .wrap()?;
        let route_id = self
            .api
            .import_remote_private_route(dht_data.data().to_vec())
            .wrap()?;
        self.out_connections.insert(dht_key.clone(), route_id);

        // Start watching this dht entry
        // trace!("Watching dht entry");
        // let expiration = Timestamp::now() + TimestampDuration::new_secs(60);
        // let subkeys = ValueSubkeyRangeSet::single(0);
        // routing
        //     .watch_dht_values(*dht_key, subkeys, expiration, 20)
        //     .await
        //     .wrap()?;

        Ok(route_id)
    }

    // Upkeep Items

    pub async fn update_route_changes(&mut self, changes: Box<VeilidRouteChange>) -> LinkResult {
        // Clean expired routes
        for route_id in changes.dead_routes {
            if self.listen_route == Some(route_id) {
                self.listen_route = None;
                continue;
            }

            // if there was a previous established route, refresh the dht entry
            if let Some(dht) = self.inc_connections.remove(&route_id) {
                trace!("connection inc route died: {}", route_id);
                if let Ok(route_id) = self.initialize_inc_route(&dht, 0).await {
                    trace!("reinitialized as {}", route_id);
                    self.inc_connections.insert(route_id, dht);
                }else{
                    trace!("failed to reinitialize");
                }
            }
        }

        // if there is no listen route, create a new one.
        let _ = self.initialize_listen_routes().await;

        // Clear outgoing routes
        // Just remove, if we need to send more, we get the new route then
        for route_id in changes.dead_remote_routes {
            trace!("remote route died: {}", route_id);
            self.out_connections.remove_by_right(&route_id);
        }
        Ok(())
    }
}
